apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: batch-services
  description: Batch related repositories
  annotations:
    backstage.io/kubernetes-id: batch-services
    snyk.io/org-id: 015ef01f-0184-4ba1-8f4d-0d90bcd025cd
    snyk.io/targets: rchaser53/batch-timer

    # backstage.io/kubernetes-id: batch-services
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-cluster: local
# spec:
#   type: service
#   lifecycle: production
#   owner: user:default/rchaser53
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
